name: flutter_farmer_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5
  google_nav_bar: 5.0.6
  line_icons: 2.0.1
  shared_preferences: 2.1.1
  geolocator: 9.0.2
  get_it: 7.6.0
  auth: ^8.2.0+2
  provider: ^6.0.5
  yandex_mapkit: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_cart: ^0.0.8
  add_to_cart_animation: ^2.0.3
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.3
  mobx_codegen: ^2.3.0
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/
    - assets/png/zlak.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
